playsound block.anvil.land master @s ~ ~ ~ 1 1
playsound block.dispenser.fail master @s ~ ~ ~ 1 1
playsound block.note_block.banjo master @s ~ ~ ~ 1 1
playsound block.note_block.basedrum master @s ~ ~ ~ 1 1
playsound block.note_block.bass master @s ~ ~ ~ 1 1
playsound block.note_block.bell master @s ~ ~ ~ 1 1
playsound block.note_block.bit master @s ~ ~ ~ 1 1
playsound block.note_block.chime master @s ~ ~ ~ 1 1
playsound block.note_block.cow_bell master @s ~ ~ ~ 1 1
playsound block.note_block.didgeridoo master @s ~ ~ ~ 1 1
playsound block.note_block.flute master @s ~ ~ ~ 1 1
playsound block.note_block.guitar master @s ~ ~ ~ 1 1
playsound block.note_block.harp master @s ~ ~ ~ 1 1
playsound block.note_block.hat master @s ~ ~ ~ 1 1
playsound block.note_block.iron_xylophone master @s ~ ~ ~ 1 1
playsound block.note_block.pling master @s ~ ~ ~ 1 1
playsound block.note_block.snare master @s ~ ~ ~ 1 1
playsound block.note_block.trumpet master @s ~ ~ ~ 1 1
playsound block.note_block.trumpet_exposed master @s ~ ~ ~ 1 1
playsound block.note_block.trumpet_oxidized master @s ~ ~ ~ 1 1
playsound block.note_block.trumpet_weathered master @s ~ ~ ~ 1 1
playsound block.note_block.xylophone master @s ~ ~ ~ 1 1